#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

app="$1"
app_dir="$PLUSHU_APPS_DIR/$app"

# For instances where a glob has no matches we want an empty list
shopt -s nullglob

addons_dir=$app_dir/addons

for target_dir in "$addons_dir"/*; do
  cidfile="$target_dir/docker/run.cid"
  if [[ -e "$cidfile" ]]; then
    service="${target_dir##*/}"
    printf '--link %q:addon_%q_link\n' \
      "$(docker inspect -f {{.Name}} $(<"$cidfile"))" "$service"
  fi
done
